/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2.main;

import java.awt.Color;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import tp2.exceptions.DebitNotSetException;
import tp2.exceptions.PuissanceNotSetException;
import tp2.turbines.Turbine;
import tp2.turbines.Turbine1;
import tp2.turbines.Turbine2;
import tp2.turbines.Turbine3;
import tp2.turbines.Turbine4;
import tp2.turbines.Turbine5;

/**
 *
 * @author arthu
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private ArrayList<Turbine> turbines = new ArrayList();
    private final static int NB_DECIMAL_MAX = 4;
    
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        E1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DebitMax1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        E2 = new javax.swing.JToggleButton();
        DebitMax2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        E3 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DebitMax3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        E4 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DebitMax4 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        E5 = new javax.swing.JToggleButton();
        DebitMax5 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        elevation_amont = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        Q_repartir = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultats = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        totalturbine = new javax.swing.JLabel();
        puissancetotal = new javax.swing.JLabel();
        reste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1110, 690));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 41, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/setting.png"))); // NOI18N
        jLabel1.setText("Configuration de la simulation");

        jPanel4.setBackground(new java.awt.Color(42, 51, 63));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Turbine 1");

        E1.setBackground(new java.awt.Color(0, 0, 0));
        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png"))); // NOI18N
        E1.setBorder(null);
        E1.setBorderPainted(false);
        E1.setContentAreaFilled(false);
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Débit max");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Turbine 2");

        DebitMax1.setBackground(new java.awt.Color(42, 51, 63));
        DebitMax1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DebitMax1.setForeground(new java.awt.Color(204, 204, 204));
        DebitMax1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DebitMax1.setText("180");
        DebitMax1.setBorder(null);

        E2.setBackground(new java.awt.Color(0, 0, 0));
        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png"))); // NOI18N
        E2.setBorder(null);
        E2.setBorderPainted(false);
        E2.setContentAreaFilled(false);
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });

        DebitMax2.setBackground(new java.awt.Color(42, 51, 63));
        DebitMax2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DebitMax2.setForeground(new java.awt.Color(204, 204, 204));
        DebitMax2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DebitMax2.setText("180");
        DebitMax2.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Débit max");

        E3.setBackground(new java.awt.Color(0, 0, 0));
        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png"))); // NOI18N
        E3.setBorder(null);
        E3.setBorderPainted(false);
        E3.setContentAreaFilled(false);
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Turbine 3");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Débit max");

        DebitMax3.setBackground(new java.awt.Color(42, 51, 63));
        DebitMax3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DebitMax3.setForeground(new java.awt.Color(204, 204, 204));
        DebitMax3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DebitMax3.setText("180");
        DebitMax3.setBorder(null);

        E4.setBackground(new java.awt.Color(0, 0, 0));
        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png"))); // NOI18N
        E4.setBorder(null);
        E4.setBorderPainted(false);
        E4.setContentAreaFilled(false);
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Turbine 4");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Débit max");

        DebitMax4.setBackground(new java.awt.Color(42, 51, 63));
        DebitMax4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DebitMax4.setForeground(new java.awt.Color(204, 204, 204));
        DebitMax4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DebitMax4.setText("180");
        DebitMax4.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Turbine 5");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Débit max");

        E5.setBackground(new java.awt.Color(0, 0, 0));
        E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png"))); // NOI18N
        E5.setBorder(null);
        E5.setBorderPainted(false);
        E5.setContentAreaFilled(false);
        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });

        DebitMax5.setBackground(new java.awt.Color(42, 51, 63));
        DebitMax5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DebitMax5.setForeground(new java.awt.Color(204, 204, 204));
        DebitMax5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DebitMax5.setText("180");
        DebitMax5.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(E1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(DebitMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(E2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(DebitMax2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(E3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DebitMax3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(E4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DebitMax4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(E5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(8, 8, 8)
                        .addComponent(DebitMax5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(DebitMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(DebitMax2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DebitMax3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DebitMax4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(DebitMax5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(34, 41, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Élévation amont");

        elevation_amont.setBackground(new java.awt.Color(34, 41, 50));
        elevation_amont.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elevation_amont.setForeground(new java.awt.Color(204, 204, 204));
        elevation_amont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elevation_amont.setText("0");
        elevation_amont.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Débit à turbiner");

        Q_repartir.setBackground(new java.awt.Color(34, 41, 50));
        Q_repartir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Q_repartir.setForeground(new java.awt.Color(204, 204, 204));
        Q_repartir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Q_repartir.setText("0");
        Q_repartir.setBorder(null);

        jButton1.setBackground(new java.awt.Color(116, 170, 239));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Lancer la simulation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Q_repartir)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(elevation_amont, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(jSeparator7)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elevation_amont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q_repartir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 690));

        jPanel2.setBackground(new java.awt.Color(70, 86, 106));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gestion de la production hydroélectrique");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel17)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 860, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(70, 86, 106));
        jLabel18.setText("Centrale des chutes du diable");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(673, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 860, 70));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        resultats.setAutoCreateRowSorter(true);
        resultats.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resultats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultats.setForeground(new java.awt.Color(70, 86, 106));
        resultats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Turbine 1", null, null, null},
                {"Turbine 2", null, null, null},
                {"Turbine 3", null, null, null},
                {"Turbine 4", null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Turbine", "Débit turbiné", "Puissance", "Hauteur de chute"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        resultats.setToolTipText("");
        resultats.setAutoscrolls(false);
        resultats.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultats.setGridColor(new java.awt.Color(255, 255, 255));
        resultats.setIntercellSpacing(new java.awt.Dimension(5, 5));
        resultats.setRowHeight(25);
        resultats.setSelectionBackground(new java.awt.Color(70, 86, 106));
        resultats.setShowHorizontalLines(false);
        resultats.setShowVerticalLines(false);
        jScrollPane1.setViewportView(resultats);
        if (resultats.getColumnModel().getColumnCount() > 0) {
            resultats.getColumnModel().getColumn(0).setResizable(false);
            resultats.getColumnModel().getColumn(0).setPreferredWidth(10);
            resultats.getColumnModel().getColumn(1).setResizable(false);
            resultats.getColumnModel().getColumn(1).setPreferredWidth(10);
            resultats.getColumnModel().getColumn(2).setResizable(false);
            resultats.getColumnModel().getColumn(2).setPreferredWidth(10);
            resultats.getColumnModel().getColumn(3).setResizable(false);
            resultats.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(70, 86, 106));
        jLabel14.setText("Débit total turbiné (m³/s)");

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(70, 86, 106));
        jLabel15.setText("Puissance Totale (MW)");

        jSeparator10.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(70, 86, 106));
        jLabel16.setText("Reste (m³/s)");

        totalturbine.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        totalturbine.setForeground(new java.awt.Color(70, 86, 106));
        totalturbine.setText("0");

        puissancetotal.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        puissancetotal.setForeground(new java.awt.Color(70, 86, 106));
        puissancetotal.setText("0");

        reste.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        reste.setForeground(new java.awt.Color(70, 86, 106));
        reste.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(totalturbine)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(puissancetotal)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(reste))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reste))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puissancetotal))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalturbine))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        // TODO add your handling code here:
        if(E1.isSelected()){
           E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_On.png")));
        }else{
           E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png")));
        }
    }//GEN-LAST:event_E1ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        // TODO add your handling code here:
        if(E2.isSelected()){
           E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_On.png")));
        }else{
           E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png")));
        }
    }//GEN-LAST:event_E2ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        // TODO add your handling code here:
        if(E3.isSelected()){
           E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_On.png")));
        }else{
           E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png")));
        }
    }//GEN-LAST:event_E3ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        // TODO add your handling code here:
        if(E4.isSelected()){
           E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_On.png")));
        }else{
           E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png")));
        }
    }//GEN-LAST:event_E4ActionPerformed

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5ActionPerformed
        // TODO add your handling code here:
        if(E5.isSelected()){
           E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_On.png")));
        }else{
           E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2/main/Toggle_Off.png")));
        }
    }//GEN-LAST:event_E5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Double elevationAmont;
        Double debitARepartir;

        int debitMax1 = Integer.parseInt(DebitMax1.getText());
        int debitMax2 = Integer.parseInt(DebitMax2.getText());
        int debitMax3 = Integer.parseInt(DebitMax3.getText());
        int debitMax4 = Integer.parseInt(DebitMax4.getText());
        int debitMax5 = Integer.parseInt(DebitMax5.getText());

        Main application = new Main();

        if(E1.isSelected()){
            Turbine t1 = new Turbine1(true, debitMax1);
            application.addTurbine(t1);
        }else{
            Turbine t1 = new Turbine1(false, debitMax1);
            application.addTurbine(t1);
        }
        if(E2.isSelected()){
            Turbine t2 = new Turbine2(true, debitMax2);
            application.addTurbine(t2);
        }else{
            Turbine t2 = new Turbine2(false, debitMax2);
            application.addTurbine(t2);
        }
        if(E3.isSelected()){
            Turbine t3 = new Turbine3(true, debitMax3);
            application.addTurbine(t3);
        }else{
            Turbine t3 = new Turbine3(false, debitMax3);
            application.addTurbine(t3);
        }
        if(E4.isSelected()){
            Turbine t4 = new Turbine4(true, debitMax4);
            application.addTurbine(t4);
        }else{
            Turbine t4 = new Turbine4(false, debitMax4);
            application.addTurbine(t4);
        }
        if(E5.isSelected()){
            Turbine t5 = new Turbine5(true, debitMax5);
            application.addTurbine(t5);
        }else{
            Turbine t5 = new Turbine5(false, debitMax5);
            application.addTurbine(t5);
        }

        elevationAmont = Double.parseDouble(elevation_amont.getText());
        debitARepartir = Double.parseDouble(Q_repartir.getText());
        try {
            application.recursion(elevationAmont, debitARepartir);
            application.resultats();
            Double D1 = 0.0, D2 = 0.0, D3 = 0.0, D4 = 0.0, D5 = 0.0;
            Double P1 = 0.0, P2 = 0.0, P3 = 0.0, P4 = 0.0, P5 = 0.0;
            Double debitAAllouer1 = 0.0, debitAAllouer2 = 0.0, debitAAllouer3 = 0.0, debitAAllouer4 = 0.0, debitAAllouer5 = 0.0 ;
            Double hChute = 0.0;
            Double hChute1 = 0.0, hChute2 = 0.0, hChute3 = 0.0, hChute4 = 0.0, hChute5 = 0.0 ;
            Double ElevQtot  = 0.0000000000008639*(debitARepartir*debitARepartir*debitARepartir*debitARepartir) - 0.000000003189*(debitARepartir*debitARepartir*debitARepartir) + 0.00000325*(debitARepartir*debitARepartir) + 0.002168*debitARepartir + 137.5 ;
            for (int i = 0; i < application.resultats().size(); i++ ) {
                Turbine turbine = application.resultats().get(i);
                if (i == 0){
                    D1 = turbine.getDebitUtilise();
                    debitAAllouer1 = debitARepartir;
                    if(E1.isSelected()){
                       hChute1 = elevationAmont - ElevQtot - ((0.000005)*(debitMax1*debitMax1)); 
                    }
                    P1 = turbine.getPuissanceGeneree();
                }
                if (i == 1){
                    D2 = turbine.getDebitUtilise();
                    debitAAllouer2 = debitARepartir - D1;
                    if(E2.isSelected()){
                        hChute2 = elevationAmont - ElevQtot - ((0.000005)*(debitMax2*debitMax2));
                    }
                    P2 = turbine.getPuissanceGeneree();
                }
                if (i == 2){
                    D3 = turbine.getDebitUtilise();
                    debitAAllouer3 = debitAAllouer2 - D2;
                    if(E3.isSelected()){
                        hChute3 = elevationAmont - ElevQtot - ((0.000005)*(debitMax3*debitMax3));
                    }
                    P3 = turbine.getPuissanceGeneree();
                }
                if (i == 3){;
                    D4 = turbine.getDebitUtilise();
                    debitAAllouer4 = debitAAllouer3 - D3;
                    if(E4.isSelected()){
                        hChute4 = elevationAmont - ElevQtot - ((0.000005)*(debitMax4*debitMax4));
                    }
                    P4 = turbine.getPuissanceGeneree();
                }
                if (i == 4){
                    D5 = turbine.getDebitUtilise();
                    debitAAllouer5 = debitAAllouer4 - D4;
                    if(E5.isSelected()){
                       hChute5 = elevationAmont - ElevQtot - ((0.000005)*(debitMax5*debitMax5)); 
                    }
                    P5 = turbine.getPuissanceGeneree();
                }
                Double debit_reparti = D1 + D2 + D3 + D4 + D5;
                Double puissance_total = P1 + P2 + P3 + P4 + P5;
                Double debit_restant = debitARepartir - D1 - D2 - D3 - D4 - D5;
                reste.setText(debit_restant+"");
                totalturbine.setText(debit_reparti+"");
                puissancetotal.setText(truncateDecimal(puissance_total,NB_DECIMAL_MAX)+"");
                resultats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Turbine 1", truncateDecimal(D1,NB_DECIMAL_MAX)+" m³/s", truncateDecimal(P1,NB_DECIMAL_MAX)+" MW", truncateDecimal(hChute1,NB_DECIMAL_MAX)+""},
                {"Turbin 2", truncateDecimal(D2,NB_DECIMAL_MAX)+" m³/s", truncateDecimal(P2,NB_DECIMAL_MAX)+" MW", truncateDecimal(hChute2,NB_DECIMAL_MAX)+""},
                {"Turbin 3", truncateDecimal(D3,NB_DECIMAL_MAX)+" m³/s", truncateDecimal(P3,NB_DECIMAL_MAX)+" MW", truncateDecimal(hChute3,NB_DECIMAL_MAX)+""},
                {"Turbin 4", truncateDecimal(D4,NB_DECIMAL_MAX)+" m³/s", truncateDecimal(P4,NB_DECIMAL_MAX)+" MW", truncateDecimal(hChute4,NB_DECIMAL_MAX)+""},
                {"Turbin 5", truncateDecimal(D5,NB_DECIMAL_MAX)+" m³/s", truncateDecimal(P5,NB_DECIMAL_MAX)+" MW", truncateDecimal(hChute5,NB_DECIMAL_MAX)+""}
            },
            new String [] {
                "Turbine", "Débit turbiné", "Puissance", "Hauteur de chute"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
            }
        } catch (DebitNotSetException ex) {
            Logger.getLogger(Ancienne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ancienne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PuissanceNotSetException ex) {
            Logger.getLogger(Ancienne.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private static BigDecimal truncateDecimal(double x,int numberofDecimals)
{
    if ( x > 0) {
        return new BigDecimal(String.valueOf(x)).setScale(numberofDecimals, BigDecimal.ROUND_FLOOR);
    } else {
        return new BigDecimal(String.valueOf(x)).setScale(numberofDecimals, BigDecimal.ROUND_CEILING);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DebitMax1;
    private javax.swing.JTextField DebitMax2;
    private javax.swing.JTextField DebitMax3;
    private javax.swing.JTextField DebitMax4;
    private javax.swing.JTextField DebitMax5;
    private javax.swing.JToggleButton E1;
    private javax.swing.JToggleButton E2;
    private javax.swing.JToggleButton E3;
    private javax.swing.JToggleButton E4;
    private javax.swing.JToggleButton E5;
    private javax.swing.JTextField Q_repartir;
    private javax.swing.JTextField elevation_amont;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel puissancetotal;
    private javax.swing.JLabel reste;
    private javax.swing.JTable resultats;
    private javax.swing.JLabel totalturbine;
    // End of variables declaration//GEN-END:variables
}
